### ISSUE TITLE
ocserv how set max-same-clients value on daloRadius

### ISSUE THREAD

**Issue by peratik** [lirantal/daloradius#106]
Hello

I installed ocserv and successfully connected to freeradius
https://github.com/openconnect/ocserv/blob/master/doc/README-radius.md

In ocserv, there is an settings for user group named "max-same-clients"

How can I define group settings on daloRadius?

Thank you

**Comment by MiguelVis** [comment]
@peratik I think you must do the following steps, in order to be able to use attributes and / or vendors not previously registered in daloRADIUS:

1. Insert the attribute from vendor (in this case the vendor is ocserv - does not exists yet, it will be also created at the same time):

![image](https://user-images.githubusercontent.com/4165032/57487944-227eef00-72b2-11e9-8cdb-68daf9b7e137.png)

the details (op, table, etc.) are up to you :)

2. Create a profile which uses this (and possibly other) attribute:

![image](https://user-images.githubusercontent.com/4165032/57488237-d5e7e380-72b2-11e9-92e5-dd75031b4266.png)

3. Create a user with this profile:

![image](https://user-images.githubusercontent.com/4165032/57488314-062f8200-72b3-11e9-88f2-f2ea618888f0.png)

or use it directly into an already existent user:

![image](https://user-images.githubusercontent.com/4165032/57488405-455dd300-72b3-11e9-9b4c-c43dec28ac16.png)

Hope it helps.

**Comment by peratik** [comment]
@MiguelVis Thank you very much for your detailed tutorial, I have set it but ocserv not reading max-same-clients from that value, Could I ask you please take a look at the problem indicated here?
https://superuser.com/questions/1435194/set-ocserv-user-config-max-same-clients-value-on-radius-side

**Comment by kkwised** [comment]
Hello
@peratik .  Please you may also have to set a rlm_sql counter in your freeradius configuration
