### ISSUE TITLE
Missing users details in accounting

### ISSUE THREAD

**Issue by Izanatos** [lirantal/daloradius#109]
Hi,

I've setup a set of Freeradius 3 servers associated with a mysql cluster.

Everything appears to work fine the only issue I am getting is empty user session details, meaning I can see total traffic data but there are no username, name, ip addresses associated. I am only getting these when I get a start message. see screenshot below

![image](https://user-images.githubusercontent.com/46830654/58695865-510e5800-838e-11e9-941a-ffd886fad0f9.png)

Any idea what I am missing here ?

Thanks,

A

**Comment by MiguelVis** [comment]
Have you created the users with daloRADIUS?

Anyway, you could inspect the Freeradius `radacct` table to see if it's saving that apparently missing data or not.

**Comment by TommasoScardi** [comment]
Hi i have a issue like that but in my case the only field that is empty is the IP ADDRESS.
Any Ideas ? Thanks
![tempsnip](https://user-images.githubusercontent.com/92218392/156600135-829eeebf-9920-4dcc-bf59-f52c6f658137.png)

**Comment by iamanjate** [comment]
I'm having a problem with daloradius, I don't know if you can help me, I created one
profile with a bandwidth of 2Mbps which is associated with a plan that
I named it 2M, which lasts for 24 hours (1 day), which I then created
a user named "jone", and when I edit the user "jone" I can see
that it is associated with this 2M plan in the "Plan Information" section, this section
and is composed of "Item Allowed by plan Used Remainning", which worries me
that in the "Allowed by plan" expected the resources that the user jone has to
disposition, "Used" resources already used by "jone" and "Remainning" what is left to
be consumed by the user, but the available values ​​do not match
because I have in "Allowed by plan" the value 0 seconds, "Used"
the value of 2 days, 20 hours, 41 minutes, 48 ​​seconds,
"Remainning" the value of -3 days, -21 hours, -42 minutes, -48 seconds,
the plan being 24 hours or 1 day.
details: the server is indicating the correct time, the management system
and database also has the correct time, and I adjusted the time-zone in
php and restarted all services but it didn't solve

**Comment by iamanjate** [comment]
I'm having a problem with daloradius, I don't know if you can help me, I created one
profile with a bandwidth of 2Mbps which is associated with a plan that
I named it 2M, which lasts for 24 hours (1 day), which I then created
a user named "jone", and when I edit the user "jone" I can see
that it is associated with this 2M plan in the "Plan Information" section, this section
and is composed of "Item Allowed by plan Used Remainning", which worries me
that in the "Allowed by plan" expected the resources that the user jone has to
disposition, "Used" resources already used by "jone" and "Remainning" what is left to
be consumed by the user, but the available values ​​do not match
because I have in "Allowed by plan" the value 0 seconds, "Used"
the value of 2 days, 20 hours, 41 minutes, 48 ​​seconds,
"Remainning" the value of -3 days, -21 hours, -42 minutes, -48 seconds,
the plan being 24 hours or 1 day.
details: the server is indicating the correct time, the management system
and database also has the correct time, and I adjusted the time-zone in
php and restarted all services but it didn't solve
![radius1](https://user-images.githubusercontent.com/126523471/221713398-7538f159-836f-4af6-ad12-1bb1ee20e0e6.JPG)
