### ISSUE TITLE
New daloRADIUS release on SourceForge?

### ISSUE THREAD

**Issue by lirantal** [lirantal/daloradius#120]
@MiguelVis awesome work 🔥🙏

Should I push a new release on SourceForge with the latest master changes?

**Comment by MiguelVis** [comment]
Hi @lirantal

Please, feel free to do whatever you want to do, as If you were the author of the 99% of daloRADIUS code. ;)

Seriously speaking, it seems to me a good idea.

But I think it should be clearly stated in SourceForge that they have to go to GitHub for issues, last state of the art code, etc., because a lot of people continues downloading old daloRADIUS version from SourceForge and asking for help there and that's a pity.

Even your daloRADIUS website mentions only SourceForge.

Taking into account that it seems that a lot of people is using daloRADIUS, I think it should be done something regarding this matter.

Oh yes, daloRADIUS is alive and growing!

:)

**Comment by lirantal** [comment]
We've already got several posts on the forums there but many back-dated tutorials still cite SourceForge as the homepage so it's inevitable that we'll get traffic there.

I'll go ahead and upload a new version there now.
Thanks! :)

**Comment by lirantal** [comment]
Released:
