### ISSUE TITLE
Deleting Attribute causes HTTP 500 error

### ISSUE THREAD

**Issue by bobby-81** [lirantal/daloradius#122]
Hi,

I'm running Raspbian Buster together with FreeRADIUS 3.0, MariaDB 10 and Daloradius and I'm trying to delete some mistaken attributes.

I noticed that when I search for, select and then try to delete an attribute in Daloradius I get a HTTP 500 error web-page.

To try and fix, as per the posting here: https://github.com/lirantal/daloradius/issues/14
I've tried opening the file:  library/opendb.php and adding:   
`$dbSocket->query("SET GLOBAL sql_mode = '';") `

Which cause a privilege issue. I then also tried adding instead:

`$dbSocket->query("SET SESSION sql_mode = '';");`

Which has no effect.

Lastly, I've changed my /library/daloradius.conf.php to `$configValues['CONFIG_DB_ENGINE'] = 'mysqli'`; and `$configValues['FREERADIUS_VERSION'] = '3'`;

Please advise what I can do to fix this issue?

Thanks!

**Comment by MiguelVis** [comment]
Hi @bobby-81 

I suspect you have an older version of daloRADIUS, because newer versions come with `mysqli `as the default database engine in configuration.

The last version of daloRADIUS is 1.1-2 from 08 Aug 2019.

You can download it from master or 1.1-2 branches.

If after update (and reconfiguration) of daloRADIUS, the issue persists, just tell us, and we'll try to catch the problem.

Tell us if that works for you.

Hope it helps.
