### ISSUE TITLE
daloRADIUS in Cloud...

### ISSUE THREAD

**Issue by siliconhippy** [lirantal/daloradius#130]
Hi Lirantal !

Sorry about wrong thread !
Can you kindly provide some details?
😝
Shippy
--------
Can daloRadius be installed in a cloud server ( AWS, Google, Azure) so it
can manage remote devices in different locations , i.e., not in the same
LAN?
@siliconhippy yes, you can install daloRADIUS in the cloud. perhaps open this question in a new issue to not hijack this one and allow others to easily find it.
-----

**Comment by lirantal** [comment]
I don't a tutorial link to give you but since this is all basically based on Linux packages, if you can run linux on it and it has the required networking connectivity then you can definitely get it to work. Moreover, you don't have to tie together the whole thing into one. FreeRADIUS can be installed on one device and MySQL+PHP (daloRADIUS) on another. The edge devices themselves don't need either of course and they are just used as the RADIUS clients.

**Comment by siliconhippy** [comment]
Thanks. 

I don't have a problem downloading your PDF but just want to know if this could work!

Also is there any support plan with daloRadius available?

1. Which client need I use on Entware? Search doesn't give me a custom link to paste here, but typing PAM and RADIUS bring up many entries that I can't tell about.

I am not a good tech, just an enthusiast with a tech degree.

2. Is openvpn and/or SSH required or desirable for the devices to server connectivity?

3. I want to start with a couple dozen devices, then scale to hundreds or more if it works out.

Basic idea: All these devices are home clients with a Linux JeOS distro for Kodi, eg discourse.coreelec.org and have one Linux image burnt on all devices, including scripts and common config with SSH root/pwd same on all devices.

So any additional configuration/ updates need to occur at first boot time, or later. Home users only need to type in a userID/password for first time authentication. Then communication will be automated.

Admin will setup database on server with each device entry that has userID, other user profile fields, and a Points Quota. 

The main function, Points Quota, will determine whether WiFi and a couple of device apps ( eg Kodi, VLC) are enabled or disabled over a given time period (weekly, monthly etc.)

MAC address is read automatically by server database upon first time user authentication. Of course admin can update database with changes anytime, requiring new user authentication.

4. So can I get some help here, assuming this all can be done with daloRadius setup?

 My preference is that the AWS or other cloud instance run all needed packages ( LAMP, daloRadius, freeRADIUS if needed, others.) Distributed mode can be done later with scale.

FYI, I was originally looking at Zeroshell OS but the cloud setup is shaky ( requires nested virtualization) and there isn't much forum support !

**Comment by lirantal** [comment]
@siliconhippy apologies for the brief response but I haven't been maintaining daloradius for years due to my move out of this industry.

let's see if others can jump into this issue to help you out.

p.s.
can you ping me on my email?

**Comment by pgupta408** [comment]
I have daloradius  up and running on Google Cloud. 

However, in status page, I do NOT see network interface attached to it. 

Is this a bug or a feature or something missing? 

Since network interface is virtual, Is this a problem? 

HTTP is working fine. 

However, I have problem in connecting NAS clients to it.
