### ISSUE TITLE
IP filtering access authorization using attributes setting on user

### ISSUE THREAD

**Issue by danialtahir** [lirantal/daloradius#167]
Hi,
I want to get help in configuring the DALORADIUS as the ip filtering authorization.
My case is, where one user can access all devices on the network and the other user can only access the certain devices, and want to control that access via a IP Control.
I know we can provide the framed ip address to the connected user, but how i can control the access of the that user on network for certain ip's or ip pool's

**Comment by Garfsfield** [comment]
If I am understanding you correctly...

One user can be associated with many different groups.

I would setup different profiles (groups) for each pool / IP range which 
have specific routing rues, and then add the user to which ever group 
they need to be in for the associated routing.

The routes would be setup in each group using the specific NAS/Routers 
command set.

Conrad

**Comment by danialtahir** [comment]
Hi Garfsfield,
Thanks for your reply, but i didnt get my answer fully yet, or may be i didnt able to convey my requirement fully.

Yes, its right that multiple groups can be associated with single user. Here i want to know that which and how should i match the attributes with the apprprioate match, and operator to achieve the ip filtering access control.

Here is the scenario, that there are 2 users, A & B. Whenever A user authenticate the network via radius the ip given to him is 192.168.200.10, and he can access these server 172.16.10.50 and 172.16.10.100, and whenever user B authenticate to network the ip given to him is 192.168.200.11 and he can only access 172.16.10.100.

So i want to know, which and how I can set the attributes to achieve this.

Just for information: In other radius server it can be achieved via Access-Control-List

**Comment by Garfsfield** [comment]
Hi Daniel

The specific device (router/NAS) that is querying the Authentication and 
Connection details from the radius server would have to be researched 
for the relevant attributes to use. (Each has their own custom attributes)

As an example, a route could be added for a user using the Cisco-Avpair 
Reply Attribute with each one using the += operator so that any previous 
entries of the same type are not replaced as they are added, this allows 
for multiple radius reply attributes of the same type to be sent to the 
Cisco device. In addition (V)irtual (R)outing and (F)orwarding van be 
setup on the Cisco device and then specifying which VRFshould be used by 
logical grouping, which can be enabled by the Cisco command: /*aaa route 
download [time] [authorization method-list]

*/For the Cisco IOS, I would recommend the following Book:
/MPLS and VPN Architectures, Volume 2//
//By Jim Guichard, Ivan Pepelnjak, Jeff Apcar/

/ - Chapter 2 has more info about this./

Group 1 would have something like this.
Cisco-AVPair = "ip:route=vrf UserA 192.168.200.11 255.255.255.255 
192.168.200.1 name UserA_R01"

Group 2
Cisco-AVPair = "ip:route=vrf UserB 172.16.10.50 255.255.255.255 
172.16.10.1 name UserB_R01"
Cisco-AVPair += "ip:route=vrf UserB 172.16.10.100 255.255.255.255 
172.16.10.1 name UserB_R02"

Using the Framed-Route attribute setup internal routes on the device 
requesting authenticated by the radius, so it only serves to advertise 
routes to addresses only accessible via that device that is connecting.

I hope this helps.

**Comment by danialtahir** [comment]
We actually want to perform authorisation, and need to apply the access control list, so that the user have limited/specific access of internal network

**Comment by MiguelVis** [comment]
This question is related to FreeRADIUS.

This document could be of help for you:
[https://networkradius.com/doc/FreeRADIUS-Technical-Guide.pdf](https://networkradius.com/doc/FreeRADIUS-Technical-Guide.pdf)

> Section 2.3 The RADIUS Session Process
