### ISSUE TITLE
Issue and Error with Attributes

### ISSUE THREAD

**Issue by collabaration** [lirantal/daloradius#188]
When trying to remove a vendor attribute the attribute is not deleted from the list of attributes for the vendor.

I'm also having an issue when trying to add an attribute from the user tab. I pick the attribute from the vendor and fill out the required information. When I attempt to apply the attribute to the user I receive the following error:

Database error
Error Message: DB Error: syntax error
Debug info: UPDATE userbillinfo SET contactperson='', planname='', company='', email='', phone='', paymentmethod='', cash='', creditcardname='', creditcardnumber='', creditcardverification='', creditcardtype='', creditcardexp='', address='', city='', state='', country='', zip='', notes='', changeuserbillinfo='0', lead='', coupon='', ordertaker='', billstatus='', nextinvoicedue='0', billdue='0', postalinvoice='', faxinvoice='', emailinvoice='', updatedate='2020-09-24 23:16:58', updateby='administrator' WHERE username='00190b840ebe' [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lead='', coupon='', ordertaker='', billstatus='', nextinvoicedue='0', billdue='0' at line 1]

Any assistance is much appreciated on these issues.

**Comment by edimondi** [comment]
@collabaration Delete mysql and install MariaDB, i had same issue

**Comment by mjducharme** [comment]
I think this issue is caused by the nextinvoicedue and billdue dates of 0

  `lastbill` date NOT NULL default '0000-00-00',
  `nextbill` date NOT NULL default '0000-00-00',

MySQL 8 seems to default to a strict mode that prevents setting a 0 date for a NOT NULL column, an attempt to do so will result in an UPDATE failure.

**Comment by lirantal** [comment]
Try MariaDB :-)

**Comment by mjducharme** [comment]
I'm sure MariaDB works as I have other systems on that that are working, but it is not always practical if you already have an established system on MySQL. Besides, it doesn't guarantee that this problem won't eventually end up affecting mariadb. A better option would be for DaloRADIUS to use a fixed real date like 0001-01-01 or something, something far enough back in the past that it wouldn't be a real invoice date, rather than using 0.

**Comment by lirantal** [comment]
Agree. Do you want to submit a PR to fix it?

**Comment by MiguelVis** [comment]
Same as #185.

**Comment by MiguelVis** [comment]
Please, check if the following SQL query solves the issue:

```
ALTER TABLE `userbillinfo`
	CHANGE COLUMN `lastbill` `lastbill` DATE NULL DEFAULT NULL AFTER `billstatus`,
	CHANGE COLUMN `nextbill` `nextbill` DATE NULL DEFAULT NULL AFTER `lastbill`;
```
