### ISSUE TITLE
Not show plan information in "daloradius-users"

### ISSUE THREAD

**Issue by nandish486** [lirantal/daloradius#241]
Hi Lirantal,

Problem with daloradius-users
when user login from daloradius-users portal, they are not able to see below thing

Item                                  	Allowed by plan	Used	Remainning
Session Time	
Session Download		333.58 Mb	
Session Upload		94.29 Mb

user have one month plan but not show in "plan information", so please provide me guideline for the same

**Comment by nandish486** [comment]
Hi Lirantal,

If you have time, so please provide me solutions.

**Comment by MiguelVis** [comment]
Hi @nandish486 .

First of all you must create / edit the plan and assign it a time **in seconds**:

![image](https://user-images.githubusercontent.com/4165032/184023539-5ba44150-e898-41ac-b03f-850f6e2d8261.png)

Then you can create / edit the user and assign the plan:

![image](https://user-images.githubusercontent.com/4165032/184023861-b5d20987-e4f3-434d-90a2-0890132e3689.png)

Please check and confirm if the issue was solved in order to close it.
