### ISSUE TITLE
Can't 1st login after fresh docker stack install daloRADIUS 2.0 beta

### ISSUE THREAD

**Issue by atmosferia-projects** [lirantal/daloradius#456]
Hi,
After a fresh install (docker-compose up) of daloRADIUS 2.0 beta, when I try to log from the frontend using the default administrator/radius account, I get a 
"Cannot Log In
If you are having trouble logging in to your account, it is likely that you have entered the wrong username and/or password. Please ensure that you have correctly entered your login credentials and try again."

I've verified the users@radius table and it exists.

After a clean startup of each container, when I tried to log again I can see this log in the database container :

2023-06-19 22:33:30 3 [Warning] Access denied for user 'root'@'172.19.0.3' (using password: NO)  <-- radius container ip
2023-06-19 22:34:13 10 [Warning] Access denied for user 'root'@'172.19.0.4' (using password: YES) <-- radius-web container ip

As far as I know, the mysql root user is limited to localhost, isn'it?
Why is radius and radius-web rto connect to the database with root credentials? In the environement vars are defined the user radius credentials, not root.

Any light?

Thanks

**Comment by atmosferia-projects** [comment]
My docker-compose file:

version: "3"

services:

  radius-mysql:
    image: mariadb:10
    container_name: radius-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radius-user-pass
      - MYSQL_ROOT_PASSWORD=root-user-pass
    volumes:
      - "/docker_external/daloradius/data/mysql:/var/lib/mysql"

  radius:
    container_name: radius
    build:
      context: .
      dockerfile: Dockerfile-freeradius
    restart: unless-stopped
    depends_on:
      - radius-mysql
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radius-user-pass
    volumes:
      - "/docker_external/daloradius/data/freeradius:/data"

  radius-web:
    build: .
    container_name: radius-web
    restart: unless-stopped
    depends_on:
      - radius
      - radius-mysql
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radius-user-pass

    volumes:
      - "/docker_external/daloradius/data/daloradius:/data"

**Comment by spady7** [comment]
Hi, I have same issue. I also granted to mysql all privileges (just for test) but issue still present.
Errors reported by @ atmosferia-projects are not present anymore, but cannot login.
Does someone can do it?
Regards

**Comment by spady7** [comment]
I am able to login but there are some steps.
The dockerfile compose does not create administrator user. This is the real problem. Also, u have to modify access to mysql with no password coming from IP of Web container. I created by hand administrator user inside mysql (userinfo tables) and i am able to login.
Anyway, i can't see no menus for admin purposes. Seams like a normale, not priviliged, user

**Comment by adarshharisree** [comment]
I am facing the same issue, any way to resolve this ??

**Comment by mtoczycki** [comment]
To resolve this go into the database, and in the radius db or whatever you named the db, you need to insert the user into user info, this seems like an oversight, because the user is added to operator, and not the user info table, so when dologin.php looks up the user, obviously the user does not exist.  This query below will add the user administrator, with the password radius, and enables the portal login, with bogus date and times.  This is for a standalone version that I run.

`INSERT INTO `userinfo` (`id`, `username`, `firstname`, `lastname`, `email`, `department`, `company`, `workphone`, `homephone`, `mobilephone`, `address`, `city`, `state`, `country`, `zip`, `notes`, `changeuserinfo`, `portalloginpassword`, `enableportallogin`, `creationdate`, `creationby`, `updatedate`, `updateby`) VALUES ('6', 'administrator', 'administrator', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'radius', '1', '2009-12-07 20:13:20', 'admin', '2009-12-07 20:13:20', 'administrator');`

The above was generated with phpMyAdmin.

This is the problem:
$sql = sprintf("SELECT COUNT(id) FROM %s WHERE ", $configValues['CONFIG_DB_TBL_DALOUSERINFO'])
         . implode(" AND ", $sql_WHERE);

The solution is to add the userinfo to the correct table on the .sql scripts, the current script shows:
`INSERT INTO `operators` VALUES (6,'administrator','radius','','','','','','','','','','','','','2009-12-07 20:13:20','2009-12-07 20:12:33','admin','2009-12-07 20:14:01','administrator');`

What should be appended to this is on the next line:
`INSERT INTO `userinfo` VALUES (6, 'administrator', 'administrator', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'radius', 1, 2009-12-07 20:13:20, 'admin', '2009-12-07 20:13:20', 'administrator');`




I hop this can help someone out there.

**Comment by mtoczycki** [comment]
Hello, could you please provide the URL that you tried to login through, you may be  using the user side login, and not the operator side login.

**Comment by gitwittidbit** [comment]
> Hello, could you please provide the URL that you tried to login through, you may be using the user side login, and not the operator side login.

Having the same problem:

When I go to the IP of my machine, I am being directed to /login.php and this does not accept administrator/radius

So what is the path for the operator side login?

Thanks

**Comment by mtoczycki** [comment]
The path for the operator side is /Dali radius/app/operators/login.php


On Sep 12, 2023, at 7:34 AM, gitwittidbit ***@***.***> wrote:

﻿
---- External Email: Use caution with attachments, links, or sharing data ----


Hello, could you please provide the URL that you tried to login through, you may be using the user side login, and not the operator side login.

Having the same problem:

When I go to the IP of my machine, I am being directed to /login.php and this does not accept administrator/radius

So what is the path for the operator side login?

Thanks

**Comment by gitwittidbit** [comment]
> The path for the operator side is /app/operators/login.php

Hmm. Not for me.

But I found out how to access the GUI in my case (using docker compose):

Under port 80 (no path) there only seems to be the normal user login.

Whereas under port 8000 (no path) there seems to be the operator login that accepts administrator/radius as login.

**Comment by mtoczycki** [comment]
In the regular install without docker the endpoints are not documented, I guess they must map the ports differently for the docker container instead of mapping the path for non docker versions.
