### ISSUE TITLE
daloradius/contrib/configs/ not working for freeradius 3.

### ISSUE THREAD

**Issue by reigelgallarde** [lirantal/daloradius#46]
I'm reporting this issue as I like daloradius.

daloradius/contrib/configs/freeradius-2.1.8 files does not work for freeradius 3.

one noticeable difference is the counter.conf is now sqlcounter.conf and of different location...
also the content of sqlcounter.conf has a lot of changes.

I tried to apply some settings from counter.conf to sqlcounter.conf but still daloradius does not work.

**Comment by lirantal** [comment]
thanks for jumping in @reigelgallarde 
if you managed to find a solution for a supported database file to import for FR3 I'd be happy to merge it in the codebase

**Comment by mjducharme** [comment]
Hi, @lirantal 

We have DaloRADIUS working with fr3 but we did it by setting it up with FR2 then upgrading FR2->FR3 and manually making the changes to the database. Everything seems to work.

I think it is probably not a good idea to have the time-saving option for the user of having a single SQL import for both freeradius and daloradius schema. The forked schema here is missing some important fixes from later schemas even in FR2 (ex. acctuniqueid field in radacct should be UNIQUE index). By having the option for the combined install it just means more problems.

It shouldn't be that hard for the user to simply import two schemas - one for freeradius and one for daloradius, as two steps instead of one, and then updates to the code become much easier. What are your thoughts on that?

**Comment by lirantal** [comment]
@mjducharme if I remember correctly in the db/ directory you also have a version of the daloradius schema only to import just that.

if you're able to provide a new fr2 schema with the updates that overwrites the older one, or even more another one that overwrites the merged schemas of fr2+dalo that will be super!

**Comment by mjducharme** [comment]
@lirantal I am wondering why you are including fr schema in your product at all. We made the mistake previously of using your combined fr2+dalo schema to set up our servers and it was missing the UNIQUE index in radacct and that wound up causing us big problems where we had lots of duplicate accounting data in radacct and it messed up our billing. It may not be much of an issue anymore since fr2 is end of life and is no longer being updated, but I would suggest actually deleting the combined schema and requiring that the person install the official schema from fr2 or fr3 plus your sql file that has only the daloradius schema. That way this problem doesn't happen to anybody else in the future.

**Comment by lirantal** [comment]
It was originally added only for convenience.

**Comment by mjducharme** [comment]
Would you be open to removing that "convenience" and making it no longer possible? If you are providing instructions anyway, the README can have the user simply import two SQL files instead of one, importing the FreeRADIUS schema SQL from the /etc/raddb directory, that way there is never the risk of your copy of the schema being out of date.

What I would propose is deleting the following four files from the repository:

- daloradius/blob/master/contrib/db/fr1-mysql-daloradius-and-freeradius.sql
- daloradius/blob/master/contrib/db/fr1-mysql-freeradius.sql
- daloradius/blob/master/contrib/db/fr2-mysql-daloradius-and-freeradius.sql
- daloradius/blob/master/contrib/db/fr2-mysql-freeradius.sql

After removing those four files, the install instructions can be amended to include the step of importing the SQL from the /etc/raddb folder, providing the precise path to it.

**Comment by lirantal** [comment]
@mjducharme Yes! sounds good to me.
I'll happily merge it in if you can create a PR and propose a good set of instructions on doing this.
