### ISSUE TITLE
Problem when downloading invoices

### ISSUE THREAD

**Issue by VictorJosso** [lirantal/daloradius#66]
Hi,

I've recently installed DaloRadius on my Pi, and I've set up my users, my groups, my plans, etc... And it works well (Thank you @lirantal for what you have done). But when I try to download or to preview invoices, I get a 500 HTTP error and my browser tells me "This page doesn't work"...

--- EDIT ---

Here are the logs of /var/log/nginx/error.log : 
`2019/01/05 22:19:06 [error] 924#924: *886 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: billinvoicesedit in /usr/share/nginx/html/daloradius/bill-invoice-edit.php on line 265" while reading upstream, client: 192.168.42.35, server: _, request: "GET /bill-invoice-edit.php?invoice_id=6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.42.38", referrer: "http://192.168.42.38/bill-invoice-list.php?user_id=5"
2019/01/05 22:19:06 [error] 924#924: *886 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: user_idTooltip in /usr/share/nginx/html/daloradius/bill-invoice-edit.php on line 354" while reading upstream, client: 192.168.42.35, server: _, request: "GET /bill-invoice-edit.php?invoice_id=6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.42.38", referrer: "http://192.168.42.38/bill-invoice-list.php?user_id=5"`

Does someone know how to fix it?
Thank you in advance, 

Victor

**Comment by MiguelVis** [comment]
Both PHP notices refer to some missing text keys in the language array / file correspoding to the language you are selected when running Daloradius.

In fact, they are not even in the language by default (English) located at:

`\daloradius\lang\en.php`

> PHP Notice: Undefined index: billinvoicesedit in /usr/share/nginx/html/daloradius/bill-invoice-edit.php on line 265

Refers to:

`<?php echo $l['helpPage']['billinvoicesedit'] ?>`

> PHP Notice: Undefined index: user_idTooltip in /usr/share/nginx/html/daloradius/bill-invoice-edit.php on line 354

Refers to :

`<?php echo $l['Tooltip']['user_idTooltip'] ?>`

The obvious solution to this problem is just adding the two missing text keys and its corresponding translations to the languages files, or, at last in the English one.

Or simply don't care about these PHP notices.

**Comment by MiguelVis** [comment]
Sorry, I had no idea. Maybe they correspond to the section title, and a tooltip explanation. Ask @lirantal .

I suposse that the problem here is that PHP version 7 is more restrictive with PHP Notices than older versions.

If you ask for a quick and dirty solution, you could do one of two things.

**1**.Add the following two lines to the file `\daloradius\lang\en.php`:
```
$l['helpPage']['billinvoicesedit'] = '';
$l['Tooltip']['user_idTooltip'] = '';
```
or

**2**.Comment the two offensive lines in the file `daloradius/bill-invoice-edit.php`:

line 265:
`// <?php echo $l['helpPage']['billinvoicesedit'] ?>`

line 354:
`// <?php echo $l['Tooltip']['user_idTooltip'] ?>`

I prefer the first option. Maybe even you could submit a PR with your patch, because it seems an old bug.
