### ISSUE TITLE
 An abnormally disconnected user of daloradius, displayed as an online user in daloRadius

### ISSUE THREAD

**Issue by ztaozhang** [lirantal/daloradius#84]
A user who is abnormally dropped in daloradius is displayed as an online user in daloRadius. If the user is always online, the account cannot be dialed, and daroradius cannot clear the disconnected user.

**Comment by MiguelVis** [comment]
Hi @ztaozhang 

> A user who is abnormally dropped in daloradius is displayed as an online user in daloRadius. If the user is always online, the account cannot be dialed, and daroradius cannot clear the disconnected user.

I suposse you wanted to say

> abnormally dropped in radius

Do you mean Freeradius? Anyway, it's the same.

What you describe in your message is something called "stale sessions", or "zombie sessions" if you prefer the term (do a search in google, and you will find lots of references to it... but no real solutions).

The problem is originated betweeen radius (freeradius?) and the nas (Mikrotik?), nothing related to daloRADIUS.

In this case, daloRADIUS only reflects the connection / user state, based on the information stored in the freeradius database (table radacct).

You will find some procedures to "clean" stale sessions, even there is one included in daloRADIUS, but I assure you that none of this procedures will solve your problem, actually.

The problem with these "solutions" is that they "close" the sessions older than X days, say 30 days.

If you have a stale session produced yesterday, your customer will have to wait for 29 days to find solved the issue. That's bad.

If you have customers that do not switch off their routers ever, you will apparently close their connections in daloRADIUS / radius, but they will be connected actually in the nas. That's bad too.

If you reduce the 30 days to, say, 1, you will apparently close a lot of connections, bla, bla, bla, as already said.

How is a stale session produced? It's simple.

When a connection is closed (normally or abnormally, we don't care) in the nas, the nas send a message to the radius server to inform about this circunstance. Then, the radius server, updates its database (table radacct) to reflect it.

But, what happens if the nas can't connect to the radius server due to whatever cause (broken connection, radius is busy, etc.)?

What happens is that the message will be lost, the radius server will never receive it, and the database of the radius server will reflect a user connection as open, when it's closed actually.

And this connection will be open forever for radius and daloRADIUS.

If you have a limit of 1 connection per user in the radius server, the user will not be able to connect ever, because when the nas ask to the radius server for a new connection, the radius server will reply "rejected, too many connections for that user".

That's all.

What's the solution?

We could consider 3 solutions:

1. Use of procedures to clean stale sessions older than X days. As already said, they are not a real solution, but they could help to maintain cleaned the radacct table.
2. Close a selected clean stale session in radacct table.
3. Develop a procedure that compares the connections between the nas and the radacct table, and clean the stale sessions.

While solucion 3 is the preferred, involves access to the nas. In Mikrotik is possible, I don't know in other nas types, but we need the credentials to access the Mikrotik via API, and daloRADIUS knows nothing about this. In fact, I developed this solution for my company, and worked well.

Then, I will go for option 2, but it involves to known the affected user.

Please, we need your feedback about this.

**Comment by MiguelVis** [comment]
I'm working in a option to close stale sessions for a user in the FreeRADIUS database.

It could be accessed from:
- Management > Users > Edit User > Close Stale Sessions button
- Config > Maintenance > Close Stale Sessions option

I will add another Operator ACL Setting for the database also.

**Comment by ztaozhang** [comment]
Very good！！！Thank you

**Comment by MiguelVis** [comment]
@ztaozhang @lirantal 

Closed with #90 

Hope it helps.
