### ISSUE TITLE
Vendor Attributes drop down not populating when trying to add new profile

### ISSUE THREAD

**Issue by bouldertatum** [lirantal/daloradius#88]
I am trying to add a new profile, but regardless of what vendor I choose, the attribute list is empty.  Because of this it isn't possible to add a new profile.  I also tried adding a new attribute and vendor under attributes, and then when going back to "new profile" vendor shows up in the drop down in  but again the added attribute does not populate in the Attribute drop down.  Any ideas?  

I am running version 0.9-9
PHP 5.4.16
MariaDB - 10.3.13

**Comment by MiguelVis** [comment]
I can't reproduce the behaviour you described. Each time I add or edit a profile, after I choose a vendor, the attribute list is populated accordingly.

Everything is all right in other field lists?

Have you tested it in more than one browser?

> I am running version 0.9-9

Download the most updated code from GitHub, master branch. The version number has not changed a lot of time ago, but there were some changes here and there since v0.9-9.

@lirantal  Maybe it's time to increment version number to reflect bug fixes or enhancements. What do you think?

> PHP 5.4.16
> MariaDB - 10.3.13

My development environment is XAMPP under Windows with:

- PHP 5.6.28
- MariaDB 10.1.19

I have access also to some installations with different environments just running fine.

**Comment by bouldertatum** [comment]
@MiguelVis - downloading the latest master branch fixed the issue.   I was confused by the version .9-9 not incrementing, but your explanation makes sense with lots of little incremental fixes.  Thanks for the help.
